# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(verbose_name='房间号')),
                ('channel_name', models.CharField(max_length=50, verbose_name='房间名')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='当前频道内成员')),
            ],
        ),
    ]
