# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_talk', '0002_auto_20190131_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='可用'),
        ),
    ]
