# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_talk', '0004_auto_20190131_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='频道主持人'),
        ),
    ]
