# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_talk', '0005_auto_20190131_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='black_list',
            field=models.ManyToManyField(related_name='be_forbiden', to=settings.AUTH_USER_MODEL, verbose_name='黑名单'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='be_members', to=settings.AUTH_USER_MODEL, verbose_name='当前频道内成员'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='be_hosts', to=settings.AUTH_USER_MODEL, verbose_name='频道主持人'),
        ),
    ]
